version: 1.2
workflows:
  # --------------------
  # Annotation Workflows
  # --------------------
  - subclass: WDL
    name: AnnotateL1MEAID
    primaryDescriptorPath: /wdl/annotation/AnnotateL1MEAID.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateMEDs
    primaryDescriptorPath: /wdl/annotation/AnnotateMEDs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateMEIs
    primaryDescriptorPath: /wdl/annotation/AnnotateMEIs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotatePALMER
    primaryDescriptorPath: /wdl/annotation/AnnotatePALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAN
    primaryDescriptorPath: /wdl/annotation/AnnotateSVAN.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAnnotate
    primaryDescriptorPath: /wdl/annotation/AnnotateSVAnnotate.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateTRs
    primaryDescriptorPath: /wdl/annotation/AnnotateTRs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /wdl/annotation/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BenchmarkAnnotations
    primaryDescriptorPath: /wdl/annotation/BenchmarkAnnotations.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  # --------------------
  # Annotation Utilities
  # --------------------
  - subclass: WDL
    name: AnnotateVcf
    primaryDescriptorPath: /wdl/annotation_utils/AnnotateVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CreatePEDAncestry
    primaryDescriptorPath: /wdl/annotation_utils/CreatePEDAncestry.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: ExtractSampleVcfs
    primaryDescriptorPath: /wdl/annotation_utils/ExtractSampleVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: FillPhasedGenotypes
    primaryDescriptorPath: /wdl/annotation_utils/FillPhasedGenotypes.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: IntegrateVcfs
    primaryDescriptorPath: /wdl/annotation_utils/IntegrateVcfs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SubsetTRGTToCatalog
    primaryDescriptorPath: /wdl/annotation_utils/SubsetTRGTToCatalog.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SubsetTsvToColumns
    primaryDescriptorPath: /wdl/annotation_utils/SubsetTsvToColumns.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SubsetVcfToContigs
    primaryDescriptorPath: /wdl/annotation_utils/SubsetVcfToContigs.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: SubsetVcfToSamples
    primaryDescriptorPath: /wdl/annotation_utils/SubsetVcfToSamples.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  # -----
  # Tools
  # -----
  - subclass: WDL
    name: HiPhase
    primaryDescriptorPath: /wdl/tools/HiPhase.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: HiPhaseMerge
    primaryDescriptorPath: /wdl/tools/HiPhaseMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  
  - subclass: WDL
    name: MinimapAlignment
    primaryDescriptorPath: /wdl/tools/MinimapAlignment.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMER
    primaryDescriptorPath: /wdl/tools/PALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMERDiploid
    primaryDescriptorPath: /wdl/tools/PALMERDiploid.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMERMerge
    primaryDescriptorPath: /wdl/tools/PALMERMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: RepeatMasker
    primaryDescriptorPath: /wdl/tools/RepeatMasker.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TRGT
    primaryDescriptorPath: /wdl/tools/TRGT.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TRGTMerge
    primaryDescriptorPath: /wdl/tools/TRGTMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: VcfDist
    primaryDescriptorPath: /wdl/tools/VcfDist.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
