version: 1.2
workflows:
  - subclass: WDL
    name: AnnotateL1MEAIDFilter
    primaryDescriptorPath: /wdl/AnnotateL1MEAIDFilter.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotatePALMER
    primaryDescriptorPath: /wdl/AnnotatePALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAN
    primaryDescriptorPath: /wdl/AnnotateSVAN.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateSVAnnotate
    primaryDescriptorPath: /wdl/AnnotateSVAnnotate.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail
    primaryDescriptorPath: /wdl/AnnotateVEPHail.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: AnnotateVEPHail_vModified
    primaryDescriptorPath: /wdl/AnnotateVEPHail_vModified.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BenchmarkAnnotations
    primaryDescriptorPath: /wdl/BenchmarkAnnotations.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: FlagSingletonReads
    primaryDescriptorPath: /wdl/FlagSingletonReads.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: MinimapAlignment
    primaryDescriptorPath: /wdl/MinimapAlignment.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMER
    primaryDescriptorPath: /wdl/PALMER.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: PALMERToVcf
    primaryDescriptorPath: /wdl/PALMERToVcf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/     

  - subclass: WDL
    name: RepeatMasker
    primaryDescriptorPath: /wdl/RepeatMasker.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TRGT
    primaryDescriptorPath: /wdl/TRGT.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: TruvariMerge
    primaryDescriptorPath: /wdl/TruvariMerge.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
