FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install VRS
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir 'ga4gh.vrs[extras]'
