FROM conda/miniconda3

RUN conda update -n base -c defaults conda

RUN conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && conda install -y htslib samtools bedtools pysam last git \
    && conda clean -a -y

WORKDIR /opt/src
RUN git clone https://github.com/xzhuo/utility.git /opt/src/utility
RUN chmod +x /opt/src/utility/limeaid.filter.pl
ENV PATH="/opt/src/utility:${PATH}"
