FROM conda/miniconda3

RUN conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && conda install -y htslib samtools bedtools pysam last git

WORKDIR /opt/src
ARG CACHEBUST=1
RUN git clone https://github.com/xzhuo/utility.git /utility
RUN chmod +x /utility/limeaid.filter.pl
ENV PATH="/opt/src/utility:${PATH}"
