FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

LABEL maintainer="Karan Jaisingh"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	cmake \
	libboost-dev \
	libcurl4-gnutls-dev \
	libhts-dev \
	pkg-config \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && \
    cd /app && \
    git clone https://github.com/ChaissonLab/vamos.git && \
	cd vamos/src/ && \
    make

ENV PATH="/app/vamos/src:${PATH}"
