FROM dfam/tetools:1.92

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install python3-pip git -y

RUN pip install matplotlib pandas pysam tqdm bio more_itertools --break-system-packages

RUN rm /opt/RepeatMasker/Libraries/famdb/*

WORKDIR /opt/src
ARG CACHEBUST=1
RUN git clone https://github.com/Markloftus/L1ME-AID.git /L1ME-AID
ENV PATH="/opt/src/L1ME-AID:${PATH}"
