FROM ubuntu:24.04

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get install -yq \
    bcftools \
    tabix \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    git \
    && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages pysam polars && \
    python3 -m pip install --break-system-packages git+https://github.com/BeckLaboratory/agglovar.git

COPY ./scripts/agglovar/run_agglovar_merge.py /opt/gnomad-lr/scripts/agglovar/
RUN chmod +x /opt/gnomad-lr/scripts/agglovar/run_agglovar_merge.py

ENV PATH="/opt/gnomad-lr/scripts/agglovar/:${PATH}"

WORKDIR /data
