FROM us.gcr.io/broad-dsde-methods/gatk-sv/sv-pipeline:2025-06-27-v1.0.4-63e6c81e

MAINTAINER Karan Jaisingh

RUN pip3 install truvari

COPY scripts/benchmark/ /opt/gnomad-lr/scripts/benchmark/
ENV PATH="/opt/gnomad-lr/scripts/benchmark/:${PATH}"
