FROM us.gcr.io/broad-dsde-methods/gatk-sv/sv-pipeline:2025-09-02-v1.0.5-631368eb

RUN wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOver \
    && chmod +x liftOver \
    && mv liftOver /opt/
RUN pip install liftover

RUN mkdir -p /opt/chain_data
RUN wget -P /opt/chain_data https://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz \
    && wget -P /opt/chain_data https://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHs1.over.chain.gz \
    && wget -P /opt/chain_data https://hgdownload.soe.ucsc.edu/goldenPath/hs1/liftOver/hs1ToHg38.over.chain.gz \
    && wget -P /opt/chain_data https://hgdownload.soe.ucsc.edu/goldenPath/hs1/liftOver/hs1ToHg19.over.chain.gz

RUN mkdir -p /opt/xz_scripts/
COPY ./scripts/liftover/UpdateVcfWithBed.py /opt/xz_scripts/UpdateVcfWithBed.py
COPY ./scripts/liftover/vcf2bed.mc_vcf.py /opt/xz_scripts/vcf2bed.mc_vcf.py
