FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    last-align \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/src
RUN git clone https://github.com/xzhuo/utility.git /opt/src/utility
RUN chmod +x /opt/src/utility/limeaid.filter.pl
ENV PATH="/opt/src/utility:${PATH}"
