FROM quay.io/ymostovoy/lr-utils-basic:2.0

MAINTAINER Karan Jaisingh

COPY ./scripts/helpers/symbalts.py /
COPY ./scripts/helpers/revert_symbalts.py /

RUN apt-get update && apt-get install python3-pip -y

RUN pip3 install pysam
