FROM us.gcr.io/broad-dsde-methods/gatk-sv/sv-pipeline:2025-06-27-v1.0.4-63e6c81e

MAINTAINER Karan Jaisingh

RUN pip3 install truvari

COPY ./scripts/benchmark/exact_match.py /opt/gnomad-lr/scripts/benchmark/
COPY ./scripts/benchmark/truvari_match.py /opt/gnomad-lr/scripts/benchmark/
COPY ./scripts/benchmark/annotate_and_benchmark.py /opt/gnomad-lr/scripts/benchmark/
COPY ./scripts/helpers/symbalts.py /opt/gnomad-lr/scripts/helpers/
COPY ./scripts/helpers/abs_svlen.py /opt/gnomad-lr/scripts/helpers/
