FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

# Install HiFiCNV
ARG HIFICNV_VERSION
RUN wget -q https://github.com/PacificBiosciences/HiFiCNV/releases/download/${HIFICNV_VERSION}/hificnv-${HIFICNV_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    && tar xzf hificnv-${HIFICNV_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
    && mv hificnv-${HIFICNV_VERSION}-x86_64-unknown-linux-gnu/hificnv /usr/local/bin/ \
    && rm -rf hificnv-${HIFICNV_VERSION}-x86_64-unknown-linux-gnu* \
    && hificnv -h
