FROM ubuntu:22.04

LABEL maintainer="Karan Jaisingh"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	build-essential \
	ca-certificates \
	cmake \
	curl \
	git \
	libboost-dev \
	libbz2-dev \
	libcurl4-gnutls-dev \
	libhts-dev \
	liblzma-dev \
	libssl-dev \
	pkg-config \
	wget \
	zlib1g-dev \
	libbz2-1.0 \
	libcurl4 \
	libhts3 \
	liblzma5 \
	samtools \
	tabix \
	zlib1g 

RUN mkdir -p /app && \
    cd /app && \
    git clone https://github.com/ChaissonLab/vamos.git && \
	cd vamos/src/ && \
    make

ENV PATH="/app/vamos/src:${PATH}"

WORKDIR /app

CMD ["/bin/bash"]
