FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Build kanpig
ARG KANPIG_VERSION
RUN wget -q https://github.com/ACEnglish/kanpig/archive/refs/tags/v${KANPIG_VERSION}.tar.gz \
    && tar xzf v${KANPIG_VERSION}.tar.gz \
    && rm v${KANPIG_VERSION}.tar.gz \
    && cd kanpig-${KANPIG_VERSION} \
    && cargo build --release \
    && mv target/release/kanpig /usr/local/bin/ \
    && cd .. \
    && rm -rf kanpig-${KANPIG_VERSION}
