FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

RUN wget https://github.com/PacificBiosciences/pb-CpG-tools/releases/download/v3.0.0/pb-CpG-tools-v3.0.0-x86_64-unknown-linux-gnu.tar.gz && \
	tar --no-same-owner -zxvf pb-CpG-tools-v3.0.0-x86_64-unknown-linux-gnu.tar.gz --directory /opt && \
	rm pb-CpG-tools-v3.0.0-x86_64-unknown-linux-gnu.tar.gz

RUN ln -s /opt/pb-CpG-tools-v3.0.0-x86_64-unknown-linux-gnu/bin/aligned_bam_to_cpg_scores /usr/local/bin/
