FROM us-central1-docker.pkg.dev/talkowski-sv-gnomad/kj-dockers/utils:latest

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    pkg-config \
    libcurl4-gnutls-dev \
    automake \
    libtool \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir "setuptools<81" && \
    pip3 install --no-cache-dir --no-build-isolation cigar && \
    pip3 install --no-cache-dir \
    "numpy>=1.19.5,<1.27.0" \
    pysam \
    biopython \
    pandas \
    scipy \
    mappy \
    pybedtools \
    scikit-learn

# Install BWA
RUN cd /opt && \
    git clone https://github.com/lh3/bwa.git && \
    cd bwa && \
    make

ENV PATH="/opt/bwa:${PATH}"

# Install minimap2
RUN cd /opt && \
    git clone https://github.com/lh3/minimap2.git && \
    cd minimap2 && \
    make && \
    curl -L https://github.com/attractivechaos/k8/releases/download/v0.2.4/k8-0.2.4.tar.bz2 | tar -jxf - && \
    cp k8-0.2.4/k8-`uname -s` k8

ENV PATH="/opt/minimap2:/opt/minimap2/misc:${PATH}"

# Install TRF
RUN cd /opt && \
    git clone https://github.com/Benson-Genomics-Lab/TRF.git && \
    cd TRF && \
    autoreconf -fi && \
    mkdir build && \
    cd build && \
    ../configure && \
    make && \
    cp src/trf /usr/local/bin/trf

# Install SVAN
RUN mkdir -p /app && \
    cd /app && \
    git clone https://github.com/REPBIO-LAB/SVAN.git

ENV PYTHONPATH="/app/SVAN:/app/SVAN/GAPI:${PYTHONPATH}"
