FROM ubuntu:22.04

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-pip \
    python3-dev \
    samtools \
    bcftools \
    tabix \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir "truvari>=5.0.0"

WORKDIR /app

CMD ["/bin/bash"]