FROM ubuntu:20.04

MAINTAINER Karan Jaisingh

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update \
	&& apt-get -y install make cmake protobuf-compiler gcc g++ zlib1g-dev libcurl4-openssl-dev libbz2-dev tree \
    liblzma-dev wget curl less pkg-config git libncurses5-dev autoconf libssl-dev \
	&& apt-get clean

# Install htslib
ENV HTSLIB_VERSION="1.20"
RUN wget -q https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& tar xjf htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& rm htslib-${HTSLIB_VERSION}.tar.bz2 \
	&& cd htslib-${HTSLIB_VERSION} \
	&& ./configure --enable-libcurl --enable-gcs --enable-s3 \
	&& make \
	&& make install \
	&& make clean \
	&& ldconfig

# Install blast
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.14.0/ncbi-blast-2.14.0+-x64-linux.tar.gz \
    && tar zxvf ncbi-blast-2.14.0+-x64-linux.tar.gz \
    && rm ncbi-blast-2.14.0+-x64-linux.tar.gz

# Install samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.13/samtools-1.13.tar.bz2 \
    && tar xvf samtools-1.13.tar.bz2 \
    && rm samtools-1.13.tar.bz2 \
    && cd samtools-1.13 \
    && ./configure \
    && make

# Install PALMER
RUN git clone https://github.com/WeichenZhou/PALMER.git \
    && cd PALMER \
    && make

ENV PATH /samtools-1.13:/ncbi-blast-2.14.0+/bin/:$PATH
