FROM quay.io/pacbio/pb_wdl_base@sha256:4b889a1f21a6a7fecf18820613cf610103966a93218de772caba126ab70a8e87

MAINTAINER Karan Jaisingh

RUN wget https://github.com/lh3/minimap2/releases/download/v2.28/minimap2-2.28.tar.bz2 \
	&& tar --no-same-owner -jxvf minimap2-2.28.tar.bz2 --directory /opt \
	&& rm minimap2-2.28.tar.bz2

RUN cd /opt/minimap2-2.28 \
	&& make -j \
	&& ln -s /opt/minimap2-2.28/minimap2 /usr/local/bin/

RUN python3 -m pip install paraphase==3.4.0
