FROM us.gcr.io/broad-dsde-methods/gatk-sv/sv-pipeline:2025-06-27-v1.0.4-63e6c81e

MAINTAINER Karan Jaisingh

RUN apt-get update && apt-get install -y build-essential r-base

COPY ./scripts/annotation/annotate_genomic_context.R /opt/gnomad-lr/scripts/annotation/
